// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Equinox.Models;

#nullable disable

namespace Project_Equinox.Migrations
{
    [DbContext(typeof(EquinoxContext))]
    [Migration("20250803060538_Phase3AdminFeatures")]
    partial class Phase3AdminFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Project_Equinox.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquinoxClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId");

                    b.HasIndex("EquinoxClassId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Project_Equinox.Models.ClassCategory", b =>
                {
                    b.Property<int>("ClassCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClassCategoryId");

                    b.ToTable("ClassCategories");

                    b.HasData(
                        new
                        {
                            ClassCategoryId = 1,
                            Name = "Boxing"
                        },
                        new
                        {
                            ClassCategoryId = 2,
                            Name = "Yoga"
                        },
                        new
                        {
                            ClassCategoryId = 3,
                            Name = "HIIT"
                        },
                        new
                        {
                            ClassCategoryId = 4,
                            Name = "Strength"
                        },
                        new
                        {
                            ClassCategoryId = 5,
                            Name = "Barre"
                        },
                        new
                        {
                            ClassCategoryId = 6,
                            Name = "Sculpt"
                        },
                        new
                        {
                            ClassCategoryId = 7,
                            Name = "Dancing"
                        },
                        new
                        {
                            ClassCategoryId = 8,
                            Name = "Running"
                        },
                        new
                        {
                            ClassCategoryId = 9,
                            Name = "Palate"
                        });
                });

            modelBuilder.Entity("Project_Equinox.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClubId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            ClubId = 1,
                            Name = "Chicago Loop",
                            PhoneNumber = "331-567-7657"
                        },
                        new
                        {
                            ClubId = 2,
                            Name = "West Chicago",
                            PhoneNumber = "331-678-3456"
                        },
                        new
                        {
                            ClubId = 3,
                            Name = "Lincoln Park",
                            PhoneNumber = "431-658-3256"
                        });
                });

            modelBuilder.Entity("Project_Equinox.Models.EquinoxClass", b =>
                {
                    b.Property<int>("EquinoxClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassPicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EquinoxClassId");

                    b.HasIndex("ClassCategoryId");

                    b.HasIndex("ClubId");

                    b.HasIndex("CoachId");

                    b.ToTable("Equinoxclasses");

                    b.HasData(
                        new
                        {
                            EquinoxClassId = 1,
                            ClassCategoryId = 1,
                            ClassDay = "Monday",
                            ClassPicture = "/images/boxing101.jpg",
                            ClubId = 1,
                            CoachId = 1,
                            Name = "Boxing 101",
                            Time = "8 AM – 9 AM"
                        },
                        new
                        {
                            EquinoxClassId = 2,
                            ClassCategoryId = 2,
                            ClassDay = "Tuesday",
                            ClassPicture = "/images/yogaflow.jpg",
                            ClubId = 2,
                            CoachId = 2,
                            Name = "Yoga Flow",
                            Time = "6 PM – 7 PM"
                        },
                        new
                        {
                            EquinoxClassId = 3,
                            ClassCategoryId = 3,
                            ClassDay = "Wednesday",
                            ClassPicture = "/images/hiitblast.jpg",
                            ClubId = 3,
                            CoachId = 3,
                            Name = "HIIT Blast",
                            Time = "5 PM – 6 PM"
                        },
                        new
                        {
                            EquinoxClassId = 4,
                            ClassCategoryId = 4,
                            ClassDay = "Thursday",
                            ClassPicture = "/images/strengthtraining.jpg",
                            ClubId = 1,
                            CoachId = 4,
                            Name = "Strength Training",
                            Time = "7 AM – 8 AM"
                        },
                        new
                        {
                            EquinoxClassId = 5,
                            ClassCategoryId = 5,
                            ClassDay = "Friday",
                            ClassPicture = "/images/barrebasic.jpg",
                            ClubId = 2,
                            CoachId = 1,
                            Name = "Barre Basics",
                            Time = "9 AM – 10 AM"
                        });
                });

            modelBuilder.Entity("Project_Equinox.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoach")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DOB = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex@equinox.com",
                            IsCoach = true,
                            Name = "Alex Smith",
                            PhoneNumber = "312-111-2222"
                        },
                        new
                        {
                            UserId = 2,
                            DOB = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@equinox.com",
                            IsCoach = true,
                            Name = "Maria Garcia",
                            PhoneNumber = "312-111-3333"
                        },
                        new
                        {
                            UserId = 3,
                            DOB = new DateTime(1992, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya@equinox.com",
                            IsCoach = true,
                            Name = "Priya Patel",
                            PhoneNumber = "312-111-4444"
                        },
                        new
                        {
                            UserId = 4,
                            DOB = new DateTime(1988, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@equinox.com",
                            IsCoach = true,
                            Name = "John Lee",
                            PhoneNumber = "312-111-5555"
                        });
                });

            modelBuilder.Entity("Project_Equinox.Models.Booking", b =>
                {
                    b.HasOne("Project_Equinox.Models.EquinoxClass", "EquinoxClass")
                        .WithMany()
                        .HasForeignKey("EquinoxClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquinoxClass");
                });

            modelBuilder.Entity("Project_Equinox.Models.EquinoxClass", b =>
                {
                    b.HasOne("Project_Equinox.Models.ClassCategory", "ClassCategory")
                        .WithMany("Classes")
                        .HasForeignKey("ClassCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Equinox.Models.Club", "Club")
                        .WithMany("Classes")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Equinox.Models.User", "Coach")
                        .WithMany("Classes")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassCategory");

                    b.Navigation("Club");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Project_Equinox.Models.ClassCategory", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Project_Equinox.Models.Club", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Project_Equinox.Models.User", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
