// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Equinox.Models;

#nullable disable

namespace Project_Equinox.Migrations
{
    [DbContext(typeof(EquinoxContext))]
    partial class EquinoxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Project_Equinox.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClubId");

                    b.ToTable("Club");

                    b.HasData(
                        new
                        {
                            ClubId = 1,
                            Name = "Bronzeville",
                            PhoneNumber = "778-404-0404"
                        },
                        new
                        {
                            ClubId = 2,
                            Name = "Andersonville",
                            PhoneNumber = "892-505-0505"
                        },
                        new
                        {
                            ClubId = 3,
                            Name = "Rogers Park",
                            PhoneNumber = "851-606-0606"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
